### ISSUE TITLE
Can't install term3 in Atom 1.39.0 / NODE_DEPRECATED

### ISSUE THREAD

**Issue by fgast** [Floobits/atom-term3#104]
I have no idea about this, so here is the full output

Atom 1.39.0 on Mac OS 10.14.6

```Installing “term3@0.22.1” failed.Hide output…

> ptyw.js@0.4.1 install /private/var/folders/hw/bbj3zxb127z_z9ngb3wt3gxc0000gn/T/apm-install-dir-119624-8660-9051hv.q72ai/node_modules/term3/node_modules/ptyw.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:86:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:79:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:1447:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/unix/pty.cc:167:21: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  String::Utf8Value file(info[0]->ToString());
                    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:178:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value arg(argv_->Get(Nan::New<Integer>(i))->ToString());
                      ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:189:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value pair(env_->Get(Nan::New<Integer>(i))->ToString());
                      ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:194:21: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  String::Utf8Value cwd_(info[3]->ToString());
                    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:374:21: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  String::Utf8Value tty_(info[1]->ToString());
                    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/fgast/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
9 warnings and 1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/hw/bbj3zxb127z_z9ngb3wt3gxc0000gn/T/apm-install-dir-119624-8660-9051hv.q72ai/node_modules/term3/node_modules/ptyw.js
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/hw/bbj3zxb127z_z9ngb3wt3gxc0000gn/T/apm-install-dir-119624-8660-9051hv.q72ai/package.json'
npm WARN apm-install-dir-119624-8660-9051hv.q72ai No description
npm WARN apm-install-dir-119624-8660-9051hv.q72ai No repository field.
npm WARN apm-install-dir-119624-8660-9051hv.q72ai No README data
npm WARN apm-install-dir-119624-8660-9051hv.q72ai No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fgast/.atom/.apm/_logs/2019-07-24T10_31_24_378Z-debug.log
```
Full Log: 
[2019-07-24T10_31_24_378Z-debug.log](https://github.com/Floobits/atom-term3/files/3426382/2019-07-24T10_31_24_378Z-debug.log)

**Comment by Verassitnh** [comment]
Exact same thing for me.
I am on `Manjaro 19.0.2`

**Comment by asherweintraub** [comment]
Same here, Windows 10.
