### ISSUE TITLE
last build term3 don't work

### ISSUE THREAD

**Issue by xGeek** [Floobits/atom-term3#17]
term3 don't work 
i've this error in the console: 
"Failed to require the main module of 'term3' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve. /usr/share/atom/resources/app.asar/src/package.js:655"

**Comment by kans** [comment]
How did you install the package?

**Comment by xGeek** [comment]
Using apm

**Comment by dbpolito** [comment]
```$ apm-beta install term3
Installing term3 to /Users/mac/.atom/packages ✗

> pty.js@0.3.0 install /private/var/folders/fr/m5rfl21519b1vy0rdt39qqv40000gp/T/apm-install-dir-1151025-34462-1kxvba4/node_modules/term3/node_modules/pty.js
> node-gyp rebuild


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/fr/m5rfl21519b1vy0rdt39qqv40000gp/T/apm-install-dir-1151025-34462-1kxvba4/node_modules/term3/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mac/.atom/.apm/.apmrc" "--userconfig" "/Users/mac/.atom/.apmrc" "install" "/private/var/folders/fr/m5rfl21519b1vy0rdt39qqv40000gp/T/d-1151025-34462-agbddv/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/fr/m5rfl21519b1vy0rdt39qqv40000gp/T/apm-install-dir-1151025-34462-1kxvba4/npm-debug.log```

**Comment by ggreer** [comment]
Can you repeat that with `apm install --verbose`? The exact error should be in the last couple hundred lines of that command.

Oh, and are you running the latest version of OS X and Atom?

**Comment by dbpolito** [comment]
verbose got really big, but this is the end:

````REQUEST end event https://registry.npmjs.org/lru-cache
REQUEST emitting complete https://registry.npmjs.org/lru-cache
REQUEST onRequestResponse https://registry.npmjs.org/depd 304 { date: 'Wed, 25 Nov 2015 16:37:46 GMT',
  via: '1.1 varnish',
  'cache-control': 'max-age=60',
  etag: '"D51XQ8IB2NO2EXAU1UFAY1A1L"',
  age: '44',
  connection: 'keep-alive',
  'x-served-by': 'cache-jfk1032-JFK',
  'x-cache': 'HIT',
  'x-cache-hits': '4',
  'x-timer': 'S1448469466.114623,VS0,VE0',
  vary: 'Accept' }
REQUEST finish init function https://registry.npmjs.org/depd
REQUEST response end https://registry.npmjs.org/depd 304 { date: 'Wed, 25 Nov 2015 16:37:46 GMT',
  via: '1.1 varnish',
  'cache-control': 'max-age=60',
  etag: '"D51XQ8IB2NO2EXAU1UFAY1A1L"',
  age: '44',
  connection: 'keep-alive',
  'x-served-by': 'cache-jfk1032-JFK',
  'x-cache': 'HIT',
  'x-cache-hits': '4',
  'x-timer': 'S1448469466.114623,VS0,VE0',
  vary: 'Accept' }
REQUEST end event https://registry.npmjs.org/depd
REQUEST emitting complete https://registry.npmjs.org/depd
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mac/.atom/.apm/.apmrc" "--userconfig" "/Users/mac/.atom/.apmrc" "install" "/private/var/folders/fr/m5rfl21519b1vy0rdt39qqv40000gp/T/d-1151025-35418-3v0i72/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above
````

Versions:

````
atom 1.3.0-beta0
apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.3
````

**Comment by kans** [comment]
This is actually a duplicate of #11.
