### ISSUE TITLE
Uncaught TypeError: Cannot read property '_selected' of null

### ISSUE THREAD

**Issue by noderat** [Floobits/atom-term3#3]
1. Pressed CTRL-C in open term3 pane

**Atom Version**: 1.0.19
**System**: linux 4.2.1-1-ARCH
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package, v0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property '_selected' of null

```
At /home/noderat/.atom/packages/term3/lib/term-view.coffee:181

TypeError: Cannot read property '_selected' of null
  at TermView.copy (/home/noderat/.atom/packages/term3/lib/term-view.coffee:181:13)
  at atom-workspace.<anonymous> (/home/noderat/.atom/packages/term3/lib/term-view.coffee:178:59)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  4x -2:36.4.0 core:confirm (div.terminal)
     -2:21.6.0 core:move-up (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  8x -2:21 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  3x -2:16 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -1:59.6.0 core:move-up (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
 14x -1:58.3.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  3x -1:48.1.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -1:28.8.0 core:delete (atom-text-editor.editor.is-focused)
     -1:28.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:11.4.0 core:confirm (div.terminal)
     -0:30.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.5.0 pane:close (atom-text-editor.editor)
  2x -0:13.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.7.0 term3:copy (div.terminal)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails"
    ]
  },
  "term3": {
    "scrollback": 5000,
    "openPanesInSameSplit": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
color-picker, v2.0.12
language-liquid, v0.4.0
linter, v1.7.2
linter-sass-lint, v0.1.5
pigments, v0.15.0
seti-icons, v0.4.5
seti-syntax, v0.4.0
seti-ui, v0.8.0
term3, v0.13.0
tool-bar, v0.1.9
tool-bar-noderat, v1.0.0

# Dev
No dev packages
```

**Comment by kans** [comment]
@noderat 

I haven't been able to reproduce this bug, but I don't doubt it exists.  Split terminals are not a feature I actively use.  I'm guessing this problem was fixed by https://github.com/Floobits/atom-term3/commit/5aa111810294fe08cacfbbc77f59bead503cc648 - which removes the copy command after terminals are closed.  

I will try to clean up splits in the near future.

**Comment by noderat** [comment]
The issue is no longer happening, I suspect [`5aa1118`](https://github.com/Floobits/atom-term3/commit/5aa111810294fe08cacfbbc77f59bead503cc648) did resolve this bug. Splits are frequently used in my agency and I've recommended they all use term3, so any effort to ensure they work properly would be incredibly helpful. Thanks!
