### ISSUE TITLE
Cannot install Atom 1.4.3

### ISSUE THREAD

**Issue by danieljoppi** [Floobits/atom-term3#33]
```bash
> pty.js@0.3.0 install /private/var/folders/4f/6jc6x7yd5q30g2cj5b4przgc0000gp/T/apm-install-dir-11615-56131-1sz6ae4/node_modules/term3/node_modules/pty.js
> node-gyp rebuild


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/4f/6jc6x7yd5q30g2cj5b4przgc0000gp/T/apm-install-dir-11615-56131-1sz6ae4/node_modules/term3/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom 2.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/daniel.joppi/.atom/.apm/.apmrc" "--userconfig" "/Users/daniel.joppi/.atom/.apmrc" "install" "/private/var/folders/4f/6jc6x7yd5q30g2cj5b4przgc0000gp/T/d-11615-56131-6ao479/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/4f/6jc6x7yd5q30g2cj5b4przgc0000gp/T/apm-install-dir-11615-56131-1sz6ae4/npm-debug.log
```

**Comment by alokjha** [comment]
Same happens for me too on Atom 1.4.3 on OS X 10.11.3

**Comment by ggreer** [comment]
It would be *really* helpful if you included the file that npm said to include with any support request. :(

**Comment by alokjha** [comment]
So I made a mistake in my comment above.
I am facing the same errors as @danieljoppi is facing on Atom 1.4.3 OS X 10.11.2 . But on OS X 10.11.3 I was able to install the package.

**Comment by danieljoppi** [comment]
My is:
 * Atom 1.4.3
 * OSX 10.11.3
 * node.js 5.5
 * npm 3.5.3

I no had this **Application/Atom** (line 6) ... The Atom 1.4.3 executable is **Application/Atom\ 2**

**Comment by amilajack** [comment]
Got the same thing on Atom Beta 1.6.0-beta

```
➜  Desktop apm-beta install term3
Installing term3 to /Users/amila/.atom/packages ✗

> pty.js@0.3.0 install /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-11621-17036-1hu3osr/node_modules/term3/node_modules/pty.js
> node-gyp rebuild


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
make: *** No rule to make target `../../../../../../../../../../../../opt/homebrew-cask/Caskroom/atom-beta/1.5.0-beta3/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom-beta/1.5.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom-beta/1.5.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-11621-17036-1hu3osr/node_modules/term3/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 15.4.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom-beta/1.5.0-beta3/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom-beta/1.5.0-beta3/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/amila/.atom/.apm/.apmrc" "--userconfig" "/Users/amila/.atom/.apmrc" "install" "/private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/d-11621-17036-1uz3ger/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-11621-17036-1hu3osr/npm-debug.log
```

**Comment by ggreer** [comment]
OK, I get that you're all having problems, but could you *please* follow the directions in the error message and **include the file**. I can't troubleshoot this without more information.

**Comment by Couto** [comment]
@ggreer It might not be that easy. I can't access the referenced file.
In my case:

```
~
❯ apm install term3
Installing term3 to /Users/couto/.atom/packages ✗

> pty.js@0.3.0 install /private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/apm-install-dir-116213-90894-19qyo1p/node_modules/term3/node_modules/pty.js
> node-gyp rebuild


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

make: *** No rule to make target `../../../../../../../../../../../../opt/homebrew-cask/Caskroom/atom-beta/1.6.0-beta0/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom-beta/1.6.0-beta0/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom-beta/1.6.0-beta0/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/apm-install-dir-116213-90894-19qyo1p/node_modules/term3/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 14.5.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom-beta/1.6.0-beta0/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom-beta/1.6.0-beta0/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/couto/.atom/.apm/.apmrc" "--userconfig" "/Users/couto/.atom/.apmrc" "install" "/private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/d-116213-90894-bpqtd1/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/apm-install-dir-116213-90894-19qyo1p/npm-debug.log


~ 9s
❯ cat /private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/apm-install-dir-116213-90894-19qyo1p/npm-debug.log
cat: /private/var/folders/z9/nzw3d7dd09xgsk7g_1p37vzh0000gn/T/apm-install-dir-116213-90894-19qyo1p/npm-debug.log: No such file or directory
```

If someone knows how to access the file, I'm more than happy to share it :(

**Comment by amilajack** [comment]
@ggreer Sorry for not including the file. I forgot to mention that I couldn't.

Here's the output of ```apm-beta install term3```:

```
...
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-116213-13085-p6lfuc/npm-debug.log
```
After getting the error, I tried to ```cat``` the file:
```
➜  cat /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-116213-13085-p6lfuc/npm-debug.log
cat: /private/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/apm-install-dir-116213-13085-p6lfuc/npm-debug.log: No such file or directory
```
"```No such file or directory```" Apparently, the file doesn't exist

**Comment by Worldrider** [comment]
I'm having exactly the same issue as @amilajackwith atom 1.6.1 and ubuntu 14.04 lts node 5.10.1 npm 3.8.5

**Comment by ggreer** [comment]
Hmm... is this error due to lack of a compiler? What happens if you run `xcodebuild` in a terminal? If it complains that no compiler is available, please follow the instructions and use `xcode-select` to install one.

**Comment by olebedev** [comment]
The same issue here - [npm-debug.log.txt](https://github.com/Floobits/atom-term3/files/223316/npm-debug.log.txt).
With:
* Atom 1.7.1
* OSX 10.10.5

**Comment by ggreer** [comment]
Can anyone who has this bug comment on whether or not they have Xcode installed?

**Comment by olebedev** [comment]
I have XCode instaled.
