### ISSUE TITLE
Uncaught TypeError: this.getActiveEditor is not a function

### ISSUE THREAD

**Issue by BuZZ-dEE** [Floobits/atom-term3#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.0
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package, v0.21.1

### Stack Trace

Uncaught TypeError: this.getActiveEditor is not a function

```
At /home/username/.atom/packages/term3/index.coffee:270

TypeError: this.getActiveEditor is not a function
    at Object.module.exports.pipeTerm (/home/username/.atom/packages/term3/index.coffee:270:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:12.8.0 core:confirm (div.terminal)
  4x -1:09.7.0 core:backspace (div.terminal)
     -1:05.7.0 core:confirm (div.terminal)
     -0:52.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:50.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:49.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 10x -0:48.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -0:44.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 10x -0:43.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:09.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:02.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 term3:pipe-path (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.22
atom-ternjs, v0.13.2
colorpicker, v0.3.0
emmet, v2.4.1
git-plus, v5.13.0
highlight-selected, v0.11.2
language-fish-shell, v1.0.2
language-svg, v0.9.0
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
pigments, v0.23.1
project-manager, v2.7.6
svg-preview, v0.7.3
term3, v0.21.1

# Dev
No dev packages
```

**Comment by BuZZ-dEE** [comment]
The error message is gone now, but I can not open Term3 with piped path.
