### ISSUE TITLE
Uncaught TypeError: Cannot set property  0  of undefined

### ISSUE THREAD

**Issue by HylloIvan** [Floobits/atom-term3#37]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.5.3 **System**: Mac OS X 10.11.2 **Thrown From**:  term3  https://github.com/Floobits/atom-term3  package, v0.21.2 ### Stack Trace Uncaught TypeError: Cannot set property  0  of undefined     At /Users/AnhTruong/.atom/packages/term3/node_modules/atom-term.js/src/term.js:2882 TypeError: Cannot set property  0  of undefined at Terminal.eraseRight  /Users/AnhTruong/.atom/packages/term3/node_modules/atom-term.js/src/term.js:2882:13  at Terminal.eraseInLine  /Users/AnhTruong/.atom/packages/term3/node_modules/atom-term.js/src/term.js:3106:12  at Terminal.WRITE  /Users/AnhTruong/.atom/packages/term3/node_modules/atom-term.js/src/term.js:1925:18  at /Users/AnhTruong/.atom/packages/term3/lib/term-view.coffee:124:15 at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25 at FUNCTION.module.exports.Emitter.simpleDispatch  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14  at Emitter.module.exports.Emitter.emit  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28  at ChildProcess. anonymous>  /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34  at emitTwo  events.js:87:13  at ChildProcess.emit  events.js:172:7  at handleMessage  internal/child_process.js:685:10  at Pipe.channel.onread  internal/child_process.js:440:11      ### Commands     -1:07.4.0 term3:OPEN  atom-text-editor.editor.is-focused  -0:23.2.0 core:move-up  atom-pane.pane.active      ### Config    json { core : {} }     ### Installed Packages    coffee # User term3, v0.21.2 # Dev No dev packages

**Comment by ggreer** [comment]
I have Byobu on OS X 10.11.3 and I can't reproduce this issue. Is there something in your Byobu config that's causing a window resize followed by a clear?
