### ISSUE TITLE
Failed to load the term3 package

### ISSUE THREAD

**Issue by Yoieh** [Floobits/atom-term3#50]
**Atom Version**: 1.7.1
**System**: Ubuntu 14.04.4
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package, v0.21.4

### Stack Trace

Failed to load the term3 package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/yoieh/.atom/packages/atom-term3/lib/term-view.coffee:3:6)
    at Object.<anonymous> (/home/yoieh/.atom/packages/atom-term3/lib/term-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/yoieh/.atom/packages/atom-term3/index.coffee:2:12)
    at Object.<anonymous> (/home/yoieh/.atom/packages/atom-term3/index.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
remote-sync, v4.0.1

# Dev
No dev packages
```

**Comment by ggreer** [comment]
This looks like a botched package installation, probably by Atom. If you uninstall/reinstall term3, does it work? If that still fails with the same error, can paste the output of `apm install term3`? (Depending on your Atom install, you may to use the exact path to `apm`.)

**Comment by Yoieh** [comment]
I sorry for late repaly. I have installed it manual. Im getting missing module when Im trying to install it by atom or with `apm install term3`.

**Comment by ggreer** [comment]
Looks like you need to install g++.

`sudo apt-get install build-essential`

**Comment by Yoieh** [comment]
Tanks silly me to not see the `make: g++: Command not found` ...
