### ISSUE TITLE
Uncaught TypeError: Expecting a function in instanceof check, but got #<Collection>

### ISSUE THREAD

**Issue by angelbotto** [Floobits/atom-term3#56]
**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package, v0.22.0

### Stack Trace

Uncaught TypeError: Expecting a function in instanceof check, but got #<Collection>

```
At /Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPropTypes.js:176

TypeError: Expecting a function in instanceof check, but got #<Collection>
    at validate (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPropTypes.js:176:38)
    at checkType (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPropTypes.js:106:14)
    at [object Object].ReactCompositeComponentMixin._checkPropTypes (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:990:30)
    at [object Object].ReactCompositeComponentMixin._processProps (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:969:14)
    at [object Object].<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:756:25)
    at [object Object].mountComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
    at [object Object].ReactMultiChild.Mixin.mountChildren (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactMultiChild.js:202:42)
    at [object Object].ReactDOMComponent.Mixin._createContentMarkup (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDOMComponent.js:198:32)
    at [object Object].<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDOMComponent.js:120:14)
    at [object Object].mountComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
    at [object Object].ReactMultiChild.Mixin._mountChildByNameAtIndex (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactMultiChild.js:399:30)
    at [object Object].ReactMultiChild.Mixin._updateChildren (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactMultiChild.js:304:16)
    at [object Object].ReactMultiChild.Mixin.updateChildren (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactMultiChild.js:254:14)
    at [object Object].ReactDOMComponent.Mixin._updateDOMChildren (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDOMComponent.js:395:12)
    at [object Object].<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDOMComponent.js:248:12)
    at [object Object].updateComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
    at [object Object].ReactComponent.Mixin.performUpdateIfNecessary (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactComponent.js:333:12)
    at [object Object].ReactComponent.Mixin.receiveComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactComponent.js:314:12)
    at [object Object].ReactDOMComponent.Mixin.receiveComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDOMComponent.js:221:43)
    at [object Object].<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1181:31)
    at [object Object].updateComponent (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1123:10)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1063:14)
    at runBatchedUpdates (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactUpdates.js:152:17)
    at ReactReconcileTransaction.Mixin.perform (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/Transaction.js:141:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/Transaction.js:141:20)
    at ReactUpdatesFlushTransaction.mixInto.perform (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
    at Object.<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
    at Object.flushBatchedUpdates (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactPerf.js:57:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/Transaction.js:214:42)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/Transaction.js:155:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
    at Object.enqueueUpdate (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
    at [object Object].ReactCompositeComponentMixin.forceUpdate (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
    at [object Object].update (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/autobinder.js:62:14)
    at Collection.<anonymous> (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/emitter.js:51:7)
    at Object.each (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/utils.js:73:16)
    at Collection.Emitter.emit (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/emitter.js:50:9)
    at Collection.DataEmitter.update (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/data_emitter.js:52:13)
    at Collection.DataCollection.add (/Users/bottico/.dotfiles/atom/packages/term3/node_modules/flukes/lib/collections.js:33:10)
    at Object.module.exports.createTermView (/Users/bottico/.dotfiles/atom/packages/term3/index.coffee:229:23)
    at Object.module.exports.newTerm (/Users/bottico/.dotfiles/atom/packages/term3/index.coffee:198:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 term3:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "spell-check",
      "tree-view",
      "gometalinter-linter",
      "jshint"
    ],
    "projectHome": "/Users/bottico/proyectos",
    "themes": [
      "one-dark-ui",
      "duotone-dark-sea-syntax"
    ]
  },
  "term3": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.21.0
api-workbench, v0.8.24
atom-emblem, v0.2.3
atom-jade, v0.3.0
atom-pair, v2.0.10
atom-xcode, v0.1.3
autocomplete-flow, v1.5.0
color-picker, v2.1.1
duotone-dark-sea-syntax, v1.0.0
editor-stats, v0.17.0
emmet, v2.4.3
environment, v1.2.0
file-icons, v1.7.6
flex-tool-bar, v0.10.0
flow-ide, v1.0.6
git-log, v0.4.1
git-time-machine, vundefined
go-config, v1.1.4
go-get, v1.0.3
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
ide-flow, v0.8.0
imdone-atom, v1.3.29
imdone-atom-github, v0.1.11
language-babel, v2.17.3
language-haml, v0.24.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-postcss, v1.2.0
language-rspec, v0.5.0
language-thrift, v1.0.2
language-tmux, v0.4.0
language-vue, v0.11.0
linter, v1.11.4
minimap, v4.22.1
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
nuclide, vundefined
pane-manager, v1.0.1
pigments, v0.26.0
project-manager, v2.9.7
raml, v0.2.0
react, v0.15.0
react-snippets, v0.4.2
rest-client, v1.1.0
ruby-block, v0.3.5
sass-comment, v1.4.0
term3, v0.22.0
time-status, v1.1.2
tool-bar, v0.4.0
travis-ci-status, v1.0.0
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by dasilvacontin** [comment]
This is a deal breaker, is not an edge-case. It happens whenever I try creating a terminal split, or I open the Tree view, causing an annoying bug pop up (anyway to disable those per plugin?).

Just letting you know, in case you thought it was a not-so-important issue. At the same time, I don't see more +1 or more reports, so I wonder if something else is going on.

**Comment by jozanza** [comment]
It's a showstopper for me as well. Would love to help fix it asap. Please let me know If I can help too. +1

**Comment by ggreer** [comment]
Hmm, looks like it's not just one person. I'll look into this. Thanks for the comments.

**Comment by dasilvacontin** [comment]
Thanks @ggreer!

**Comment by dasilvacontin** [comment]
@ggreer, do you need a hand? Have you been able to start digging? No worries in any case.

**Comment by ggreer** [comment]
It's related to https://github.com/atom/atom/issues/12024. I've submitted a fix: https://github.com/atom/atom/pull/12028

**Comment by dasilvacontin** [comment]
tyvm @ggreer!

**Comment by matths** [comment]
Atom Version: 1.7.2
System: Mac OS X 10.10.5
Thrown From: term3 package, v0.22.1

error's still there

**Comment by ggreer** [comment]
While my PR was merged into Atom master, the fix is slated for the Atom 1.10 release. I'll close this issue once 1.10 comes out.

**Comment by pimentel** [comment]
Still having this issue with Atom 1.10.2 on Mac 10.10.5 with term3 v0.22.1.

Any updates?

Thanks in advance!
