### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by STBTMTR** [Floobits/atom-term3#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package, v0.22.1

### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactMount.js:510

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactMount.js:510:50)
    at findParent (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactEventListener.js:46:30)
    at handleTopLevelImpl (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactEventListener.js:81:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/Transaction.js:141:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
    at Object.batchedUpdates (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactUpdates.js:113:20)
    at ReactEventListener.dispatchEvent (/Users/vlodvwv/.atom/packages/term3/node_modules/react-atom-fork/lib/ReactEventListener.js:186:20)
```

### Commands

```
     -6:42.2.0 autocomplete-plus:activate (atom-text-editor#core.ignoredNames.editor.mini)
     -6:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:34.9.0 autocomplete-plus:activate (atom-text-editor#core.ignoredNames.editor.mini)
     -6:33.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:31.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:16 core:move-right (atom-text-editor.editor.is-focused)
  2x -6:15.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:06.2.0 autocomplete-plus:activate (atom-text-editor#core.ignoredNames.editor.mini)
     -5:58.4.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -5:53.8.0 autocomplete-plus:activate (atom-text-editor#core.ignoredNames.editor.mini)
     -5:52.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:51.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:06.3.0 script:run (atom-text-editor.editor.is-focused)
  2x -4:06.0 script:kill-process (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -3:56.3.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "rails-snippets",
      "json-schema"
    ],
    "ignoredNames": [
      ".meta",
      "*.meta",
      ".DS_Store"
    ],
    "projectHome": "/Users/vlodvwv/",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "term3": {
    "fontFamily": "Monaco",
    "fontSize": "11"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-yeoman, v0.3.15
autocomplete-paths, v1.0.2
autocomplete-plus, v2.31.0
autocomplete-python, v1.8.1
autocomplete-ruby, v0.1.0
autohide-tree-view, v0.25.1
browser-plus, v0.0.60
file-icons, v1.7.15
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
line-jumper, v0.14.1
linter, v1.11.14
linter-python, v2.1.7
linter-ruby, v1.2.2
local-history, v3.3.0
minimap, v4.24.6
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.1
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
monokai, v0.18.0
open-recent, v5.0.0
project-manager, v2.9.7
python-debugger, v0.1.0
python-indent, v0.4.3
python-tools, v0.6.7
regex-railroad-diagram, v0.16.0
ruby-block, v0.3.5
ruby-define-method, v0.2.2
ruby-slim, v0.2.0
ruby-syntax-replacer, v0.5.1
script, v3.7.3
show-ideographic-space, v1.0.1
symbols-tree-view, v0.13.2
tag, v0.4.0
term3, v0.22.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by gcampfield** [comment]
+1
