### ISSUE TITLE
Can not install in macOS Sierra

### ISSUE THREAD

**Issue by montogeek** [Floobits/atom-term3#79]
This is the output:

```
> ptyw.js@0.4.1 install /private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/apm-install-dir-11695-58852-1fqzi77/node_modules/term3/node_modules/ptyw.js
> node-gyp rebuild

/private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/apm-install-dir-11695-58852-1fqzi77
`-- (empty)


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/apm-install-dir-11695-58852-1fqzi77/node_modules/term3/node_modules/ptyw.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/apm-install-dir-11695-58852-1fqzi77/package.json'
npm WARN apm-install-dir-11695-58852-1fqzi77 No description
npm WARN apm-install-dir-11695-58852-1fqzi77 No repository field.
npm WARN apm-install-dir-11695-58852-1fqzi77 No README data
npm WARN apm-install-dir-11695-58852-1fqzi77 No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/montogeek/.atom/.apm/.apmrc" "--userconfig" "/Users/montogeek/.atom/.apmrc" "install" "/private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/d-11695-58852-ze8tjx/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ptyw.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/5j/8b0qwgz16c78hqx2c6xc1wq40000gn/T/apm-install-dir-11695-58852-1fqzi77/npm-debug.log
npm ERR! code 1
```

I know that the error is caused by a new installation of XCode tools, but when running a command in my console everything is fine, makes me think that this package are compiled with a different environment.

**Comment by montogeek** [comment]
Solved after running `sudo xcodebuild -license` :)
