### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by leomayer** [Floobits/atom-term3#88]
I tried to install this plugin but it fails under 1.14.3 x64, OpenSuSe

The log-file says:

Installing “term3@0.22.1” failed.Hide output…
/bin/bash: mc: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/bash: Fehler beim Importieren der Funktionsdefinition für `mc'.

> ptyw.js@0.4.1 install /tmp/apm-install-dir-11728-5200-15flp94/node_modules/term3/node_modules/ptyw.js
> node-gyp rebuild

/tmp/apm-install-dir-11728-5200-15flp94
└── (empty)

npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
sh: mc: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
sh: Fehler beim Importieren der Funktionsdefinition für `mc'.
sh: mc: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
sh: Fehler beim Importieren der Funktionsdefinition für `mc'.
/bin/bash: mc: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/bash: Fehler beim Importieren der Funktionsdefinition für `mc'.
/bin/sh: mc: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/sh: Fehler beim Importieren der Funktionsdefinition für `mc'.
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.9-1-default
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11728-5200-15flp94/node_modules/term3/node_modules/ptyw.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11728-5200-15flp94/package.json'
npm WARN apm-install-dir-11728-5200-15flp94 No description
npm WARN apm-install-dir-11728-5200-15flp94 No repository field.
npm WARN apm-install-dir-11728-5200-15flp94 No README data
npm WARN apm-install-dir-11728-5200-15flp94 No license field.
npm ERR! Linux 4.9.9-1-default
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/lw/.atom/.apm/.apmrc" "--userconfig" "/home/lw/.atom/.apmrc" "install" "/tmp/d-11728-5200-p1ede/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ptyw.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11728-5200-15flp94/npm-debug.log
npm ERR! code 1

**Comment by leomayer** [comment]
Note: When I type in mc ==> Midnight Commander is launched - which makes no sense within Atom...

**Comment by Guriam** [comment]
Install npm on your linux distro.

**Comment by sunjay** [comment]
Installing npm (and node) fixes this issue for me.

**Comment by kylebarron** [comment]
I have a similar bug, but I've installed both npm and node. I'm running Ubuntu 16.04.

atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

node --version
v6.10.3

npm --version
3.10.10


apm install term3
Installing term3 to /home/kyle/.atom/packages ✗

> ptyw.js@0.4.1 install /tmp/apm-install-dir-11755-9614-m7snyj.xii9zilik9/node_modules/term3/node_modules/ptyw.js
> node-gyp rebuild

/tmp/apm-install-dir-11755-9614-m7snyj.xii9zilik9
└── (empty)


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11755-9614-m7snyj.xii9zilik9/node_modules/term3/node_modules/ptyw.js
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11755-9614-m7snyj.xii9zilik9/package.json'
npm WARN apm-install-dir-11755-9614-m7snyj.xii9zilik9 No description
npm WARN apm-install-dir-11755-9614-m7snyj.xii9zilik9 No repository field.
npm WARN apm-install-dir-11755-9614-m7snyj.xii9zilik9 No README data
npm WARN apm-install-dir-11755-9614-m7snyj.xii9zilik9 No license field.
npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/kyle/.atom/.apm/.apmrc" "--userconfig" "/home/kyle/.atom/.apmrc" "install" "/tmp/d-11755-9614-5kuyq8.cvl81if6r/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ptyw.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11755-9614-m7snyj.xii9zilik9/npm-debug.log
npm ERR! code 1

**Comment by kylebarron** [comment]
This is due to a [known issue](https://github.com/atom/apm/issues/698) in apm. [This fix](https://github.com/atom/apm/issues/698#issuecomment-293814930) worked for me. Namely, I went into /usr/share/atom/resources/app/apm/bin and changed the requisite lines in python-interceptor.sh from python to python2. Then term3 successfully built for me.

**Comment by ghost** [comment]
I ran into similar problems. Here is how I believe I got it working:

Install MS components needed for build: I used windows-build-tools
Download and install .Net Framework 4.5 (needed for windows 7 machine)
install windows build tools
npm install --global windows-build-tools

**Comment by paulrm** [comment]
I ran into similar problems with Ubuntu 18.04.3 LTS (Bionic Beaver)
Even I tried the [fix](https://github.com/atom/apm/issues/698#issuecomment-293814930), still failing 

atom --version
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 2.7.17
git 2.17.1
