### ISSUE TITLE
electron prebuilt does fails to run, but does run from OS X terminal

### ISSUE THREAD

**Issue by AddictArts** [Floobits/atom-term3#9]
```
$./node_modules/.bin/electron .
module.js:338
    throw err;
    ^

Error: Cannot find module 'app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/somebody/box/atom/photon-0.1.2-dist/template-app/app.js:1:90)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by kans** [comment]
I'm guessing the actual problem is that you built t3 against a different node than what shell runs?  T3 uses the native module pty.js (which binds libterm).

**Comment by AddictArts** [comment]
I worded this poorly. What I am saying is that an electron project will run from an OS X terminal fine. But if I try to run it from a t3 I get the error above. Hope that explains it better. Thanks @kans
