### ISSUE TITLE
Failed to activate the term3 package

### ISSUE THREAD

**Issue by jgeluk** [Floobits/atom-term3#92]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [term3](https://github.com/Floobits/atom-term3) package 0.22.1

### Stack Trace

Failed to activate the term3 package

```
At ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'

Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:20965:56)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:20937:27)
  at <embedded>:68653:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:68651:65)
  at <embedded>:68245:23
  at Package.module.exports.Package.measure (<embedded>:68207:21)
  at Package.module.exports.Package.finishLoading (<embedded>:68241:25)
  at PackageManager.module.exports.PackageManager.loadAvailablePackage (<embedded>:20322:38)
  at PackageManager.module.exports.PackageManager.loadPackage (<embedded>:20296:27)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20444:36)
  at Object.activate (/packages/term3/index.coffee:138:19)
  at Package.module.exports.Package.activateNow (<embedded>:68361:25)
  at <embedded>:68333:38
  at Package.module.exports.Package.measure (<embedded>:68207:21)
  at <embedded>:68326:32
  at Package.module.exports.Package.activate (<embedded>:68323:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20446:40)
  at <embedded>:20427:35
  at Config.module.exports.Config.transactAsync (<embedded>:17520:24)
  at PackageManager.module.exports.PackageManager.activatePackages (<embedded>:20422:25)
  at PackageManager.module.exports.PackageManager.activate (<embedded>:20404:52)
  at <embedded>:1085:34

```

### Commands

```
  2x -0:37.4.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
auto-update-packages 1.0.1 
autocomplete-modules 1.6.10 
docblockr 0.10.3 
editorconfig 2.2.2 
git-projects 1.17.0 
language-babel 2.65.0 
nuclide 0.229.0 
sync-settings 0.8.1 
term3 0.22.1 
```

**Comment by ghost** [comment]
I ran into similar problems. Here is how I believe I got it working:

Install MS components needed for build: I used windows-build-tools
Download and install .Net Framework 4.5 (needed for windows 7 machine)
install windows build tools
npm install --global windows-build-tools
