### ISSUE TITLE
cannot install term/2/3

### ISSUE THREAD

**Issue by wenmm** [Floobits/atom-term3#97]
> ptyw.js@0.4.1 install C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\node_modules\term3\node_modules\ptyw.js
> node-gyp rebuild

C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\node_modules\term3\node_modules\ptyw.js>if not defined npm_config_node_gyp (node "C:\Users\haimei\AppData\Local\atom\app-1.21.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\haimei\AppData\Local\atom\app-1.21.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\node_modules\term3\node_modules\ptyw.js\build\vendor\winpty\winpty-agent.vcxproj(20,3): error MSB4019: δ�ҵ� ��������Ŀ��C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props������ȷ�� <Import> �����е�·����ȷ���Ҵ����ϴ��ڸ��ļ���
C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\node_modules\term3\node_modules\ptyw.js\build\vendor\winpty\winpty.vcxproj(20,3): error MSB4019: δ�ҵ���� �����Ŀ��C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props������ȷ�� <Import> �����е�·����ȷ���Ҵ����ϴ��ڸ��ļ���
C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9
`-- (empty)

npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\haimei\AppData\Local\atom\app-1.21.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\haimei\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\haimei\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\node_modules\term3\node_modules\ptyw.js
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\package.json'
npm WARN apm-install-dir-117109-9172-1xze35o.i6th60qkt9 No description
npm WARN apm-install-dir-117109-9172-1xze35o.i6th60qkt9 No repository field.
npm WARN apm-install-dir-117109-9172-1xze35o.i6th60qkt9 No README data
npm WARN apm-install-dir-117109-9172-1xze35o.i6th60qkt9 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\haimei\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\haimei\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\haimei\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\haimei\\.atom\\.apmrc" "install" "C:\\Users\\haimei\\AppData\\Local\\Temp\\d-117109-9172-i9ngtc.b0fvhlrf6r\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ptyw.js@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ptyw.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\haimei\AppData\Local\Temp\apm-install-dir-117109-9172-1xze35o.i6th60qkt9\npm-debug.log
npm ERR! code 1

**Comment by n3onfist** [comment]
i got same error..help needed..thanks in advanced

OS: Windows 10
Atom version: 1.25.0 x64
node -v v6.9.5
node-gyp -v v3.4.0
npm  v3.10.10

**Comment by ghost** [comment]
I ran into similar problems. Here is how I believe I got it working:

Install MS components needed for build: I used windows-build-tools
Download and install .Net Framework 4.5 (needed for windows 7 machine)
install windows build tools
npm install --global windows-build-tools
